const $=id=>document.getElementById(id);let currentPlan=null;
function addSubject(name="",topics=""){const wrap=document.createElement("div");wrap.className="subject-row";wrap.innerHTML=`<div class="subject-top"><input class="subject-name" placeholder="Subject name (e.g. Mathematics)" value="${escapeHtml(name)}" required><button type="button" title="Remove subject" aria-label="Remove subject">×</button></div><textarea class="subject-topics" placeholder="Topics separated by commas (e.g. Matrices, Calculus, Probability)">${escapeHtml(topics)}</textarea>`;wrap.querySelector("button").onclick=()=>wrap.remove();$("subjects").appendChild(wrap)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
addSubject("Mathematics","Algebra, Calculus, Probability");addSubject("Physics","Mechanics, Electricity, Optics");addSubject("Chemistry","Chemical bonding, Equilibrium, Organic chemistry");
const d=new Date();d.setDate(d.getDate()+14);$("examDate").value=d.toISOString().slice(0,10);$("examDate").min=new Date().toISOString().slice(0,10);
$("addSubject").onclick=()=>addSubject();
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2800)}
$("plannerForm").onsubmit=async e=>{e.preventDefault();const subjects=[...document.querySelectorAll(".subject-row")].map(r=>({name:r.querySelector(".subject-name").value.trim(),topics:r.querySelector(".subject-topics").value.split(",").map(x=>x.trim()).filter(Boolean),level:$("level").value==="Beginner"?"Needs work":$("level").value})).filter(s=>s.name);if(!subjects.length){toast("Add at least one subject.");return}const btn=$("generate");btn.disabled=true;btn.innerHTML="✦ Creating your plan...";try{const payload={goal:$("goal").value,subjects,examDate:$("examDate").value,hoursPerDay:Number($("hours").value),level:$("level").value,notes:$("notes").value};const r=await fetch("/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error||"Could not create plan");const data=await r.json();currentPlan=data.plan;renderPlan(data.plan);$("results").classList.remove("hidden");$("results").scrollIntoView({behavior:"smooth"});toast(data.mode==="ai"?"AI study plan created!":"Study plan created in demo mode.");}catch(err){toast(err.message+" — using offline planner.");currentPlan=localPlan(subjects,$("examDate").value,Number($("hours").value));renderPlan(currentPlan);$("results").classList.remove("hidden")}finally{btn.disabled=false;btn.innerHTML='<span>✦</span> Generate my study plan <b>→</b>'}};
function localPlan(subjects,date,hours){let end=new Date(date+"T00:00:00"),start=new Date();start.setHours(0,0,0,0);let n=Math.max(1,Math.min(30,Math.ceil((end-start)/86400000))),topics=subjects.flatMap(s=>s.topics.map(t=>({subject:s.name,topic:t})));if(!topics.length)topics=subjects.map(s=>({subject:s.name,topic:"Core concepts and practice"}));let days=[];for(let i=0;i<n;i++){let dt=new Date(start);dt.setDate(dt.getDate()+i);let tasks=[];for(let j=0;j<Math.max(1,Math.floor(hours*60/50));j++){let t=topics[(i*Math.max(1,Math.floor(hours*60/50))+j)%topics.length];tasks.push({...t,minutes:50,priority:j===0?"High":"Medium",reason:"Focused learning and practice."})}days.push({date:dt.toISOString().slice(0,10),focus:i===n-1?"Final revision":`Learning and practice · Day ${i+1}`,tasks})}return{title:"Your personalized study plan",overview:`${n} days · ${hours} study hours per day. Your schedule is a flexible guide.`,days,tips:["Use active recall and practice questions.","Take short breaks between focused blocks.","Review difficult topics regularly."]}}
function renderPlan(p){$("planTitle").textContent=p.title||"Your personalized study plan";$("planOverview").textContent=p.overview||"";$("planDays").innerHTML=(p.days||[]).map((day,i)=>`<article class="day-card"><h4>Day ${i+1} <span class="date">· ${escapeHtml(day.date||"")}</span></h4><div class="focus">${escapeHtml(day.focus||"Study session")}</div>${(day.tasks||[]).map(t=>`<div class="task"><div><b>${escapeHtml(t.subject||"Study")}</b><small>${escapeHtml(t.topic||"Topic")}</small></div><div class="task-meta">${Number(t.minutes)||45} min<br><span class="priority">${escapeHtml(t.priority||"Medium")}</span></div></div>`).join("")}</article>`).join("");}
$("adaptBtn").onclick=async()=>{const update=$("updateText").value.trim();if(!update||!currentPlan){toast("Describe what changed first.");return}const btn=$("adaptBtn");btn.disabled=true;btn.textContent="Thinking...";try{const r=await fetch("/api/adapt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:currentPlan,update})});if(!r.ok)throw new Error("Adaptation unavailable");const data=await r.json();$("adaptResult").innerHTML=`<b>${escapeHtml(data.message||"Here's how to adjust your plan:")}</b>${data.changes?.length?`<ul>${data.changes.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`:""}${data.suggestions?.length?`<ul>${data.suggestions.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`:""}${data.nextSteps?.length?`<p><b>Next steps</b></p><ul>${data.nextSteps.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`:""}`;$("adaptResult").classList.remove("hidden");toast(data.mode==="ai"?"Plan adaptation ready.":"Offline suggestions ready.");}catch(e){$("adaptResult").textContent="Move unfinished work to the next open block, reduce a lower-priority task if needed, and protect time for revision.";$("adaptResult").classList.remove("hidden")}finally{btn.disabled=false;btn.textContent="Adapt my plan →"}};
$("printBtn").onclick=()=>window.print();$("howBtn").onclick=()=>toast("Add your topics, generate a roadmap, then adapt it as you progress.");